### ISSUE TITLE
Suspect wave ht data from Mayflower buoy

### ISSUE THREAD

**Issue by tshyka** [gulfofmaine/Neracoos-1-Buoy-App#1127]
The Mayflower buoy is reporting wave heights of 106 feet and wave period of 47 seconds, which I suspect is bad data. Can you turn off the wave data from the Mayflower buoy.
![Screen Shot 2021-03-12 at 10 12 48 AM](https://user-images.githubusercontent.com/22799875/110959346-97db0100-831b-11eb-844c-61892ec3f10f.png)

**Comment by youngmorse** [comment]
Hi Tom,

It looks like they started sending us new data (wind speed/direction) without giving us a heads up. The values were in the middle of the feed, not the beginning or the end and everything shifted a column. So water temperature was actually the new wind direction, wave height water temp, etc. We turned off the buoy to fix the scripts. Dylan got the parser updated, but we do want to confirm the variables/units for these variables since they did not send them.  I’m sending an email to Fugro and Shell this morning.

The old buoy map is a little more challenging to update, but we’ll get that sorted out as well.

Thanks!
Riley


On March 12, 2021 at 10:14:28 AM, Tom Shyka ***@***.******@***.***>) wrote:

The Mayflower buoy is reporting wave heights of 106 feet, which I suspect is bad data. Can you turn off the wave ht data from the Mayflower buoy.
[Screen Shot 2021-03-12 at 10 12 48 AM]<https://user-images.githubusercontent.com/22799875/110959346-97db0100-831b-11eb-844c-61892ec3f10f.png>

**Comment by tshyka** [comment]
Thanks for the update, great to hear that we are getting wind speed but
that sucks that it messed up the data ingest.

**Comment by Dylan-Pugh** [comment]
This has been corrected and the correct data is being shown in ERDDAP/Mariner's Dashboard. I'll go ahead and close unless there are other concerns.
![Screen Shot 2021-03-15 at 15 34 01](https://user-images.githubusercontent.com/31519230/111210721-f9ad9c00-85a3-11eb-8782-0714effc42ac.png)

**Comment by tshyka** [comment]
Excellent, thank you!
