### ISSUE TITLE
Slow loading with Next.js

### ISSUE THREAD

**Issue by abkfenris** [gulfofmaine/Neracoos-1-Buoy-App#3083]
It looks like React-Query have updated some of their suggestions on how to play with the Next.js app router: https://tanstack.com/query/latest/docs/framework/react/guides/advanced-ssr#alternative-use-a-single-queryclient-for-prefetching

There are probably some places we can optimize and pre-fetch better, and others where we can get the right loading transition to give better feedback.
```[tasklist]
### Tasks
- [ ] Perfomance monitoring
- [ ] https://github.com/gulfofmaine/Neracoos-1-Buoy-App/pull/3103
- [ ] Hack large chunks out to get a rough idea where slowness is happening
```

**Comment by Adelle-Pitsas** [comment]
Working on this. I think generally there are a lot of places we are using `use client` where we should be using server components that would prevent us from using the single query client for prefetching approach. Refactoring them to server components has proven to be a bit of a bear. One issue we might be facing is frequently cold starting, where pages take significantly longer to load if a user hasn't hit that endpoint within the recent past (from what I've read 5ish mins). 

For the time being, loading transitions seem to be a good bandaid, but it'd be good to figure out an effective pre-fetch strategy to follow in the future. Also found some folks who may be struggling with similar issues....

https://www.reddit.com/r/nextjs/comments/1at62b5/slow_server_response_on_first_load_using_ssg/
https://www.reddit.com/r/nextjs/comments/zhrx41/waiting_for_server_response_is_taking_too_much/

**Comment by abkfenris** [comment]
I may have linked to the wrong part of react-query doc. What if we start with a top level prefetch of platforms that is cached longer on the server, then have a shorter cache time on the client?

**Comment by Adelle-Pitsas** [comment]
What's been tried:
- Moving components to server side rendering--removing "use client" (Adelle)
  - Doesn't make anything any faster and also is not compatible with our built infrastructure
- Adding `loading.ts` to slow loading routes (Adelle)
  - Doesn't improve routing loading time (the main issue), but is probably a good practice for slower loading components in the future
- Refactor to `getServerSideProps` (Adelle)
  - Isn't compatible with how we are fetching our data (we aren't always fetching in routes)
- Added `Suspense` boundaries (Adelle)
  - This was at the beginning of this journey when I thought the data was the cause of the slow loading. Did nothing and didn't use the fallback component, mainly because this is mostly a routing issue.

**Comment by abkfenris** [comment]
Largely closed by https://github.com/gulfofmaine/Neracoos-1-Buoy-App/pull/3108

**Comment by abkfenris** [comment]
One way that we could explore speeding things up further is to move to having Cloudflare host it at the edge (POPs in Boston, Bangor, and NYC).

- https://opennext.js.org/
